version: '3'

vars:
  ROOT_DIR:
    sh: git rev-parse --show-toplevel

tasks:
  build:
    aliases: [b]
    cmds:
      - go build -o gh-pm main.go
      - task: logi-"Build completed"
      - gh extension remove gh-pm
      - task: logw-"Removing previous version"
      - gh extension install . --force
      - task: logi-"Install completed"
    silent: true
  generate:
    aliases: [g]
    cmds:
      - defer: rm -rf types
      - task: mock:fetch-data
      - task: mock:jsonpkl-cards.json
      - task: mock:jsonpkl-issues.json
      - task: mock:jsonpkl-milestones.json
      - task: mock:jsonpkl-prs.json
      - task: mock:jsonpkl-projects.json
      - task: mock:jsonpkl-releases.json
      - task: mock:jsonpkl-user.json
  test:
    aliases: [t]
    cmds:
      - go test -v ./...
    silent: true
    
includes:
  log:
    taskfile: ./Util/Log.yml
    dir: "{{.ROOT_DIR}}"
    flatten: true
  mock:
    taskfile: ./Util/Mock.yml
    dir: "{{.ROOT_DIR}}"
    internal: true
  pkgs:
    taskfile: ./Env/Pkgs.yml
    dir: "{{.ROOT_DIR}}"
    internal: true
