# https://taskfile.dev

version: '3'
silent: true

vars:
  ROOT_DIR:
    sh: git rev-parse --show-toplevel

includes:
  dev: 
    taskfile: .taskfiles/Dev.yml
    flatten: true
    dir: .

tasks:
  default:
    cmds:
      - task -l
    silent: true
