// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type MilestonesListJson []MilestonesJson

type MilestonesJson struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Number corresponds to the JSON schema field "number".
	Number float64 `json:"number" yaml:"number" mapstructure:"number"`

	// ProgressPercentage corresponds to the JSON schema field "progressPercentage".
	ProgressPercentage float64 `json:"progressPercentage" yaml:"progressPercentage" mapstructure:"progressPercentage"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state" yaml:"state" mapstructure:"state"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}
