// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type ReleasesListJson []ReleasesJson

type ReleasesJson struct {
	// IsDraft corresponds to the JSON schema field "isDraft".
	IsDraft bool `json:"isDraft" yaml:"isDraft" mapstructure:"isDraft"`

	// IsLatest corresponds to the JSON schema field "isLatest".
	IsLatest bool `json:"isLatest" yaml:"isLatest" mapstructure:"isLatest"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// PublishedAt corresponds to the JSON schema field "publishedAt".
	PublishedAt string `json:"publishedAt" yaml:"publishedAt" mapstructure:"publishedAt"`

	// TagName corresponds to the JSON schema field "tagName".
	TagName string `json:"tagName" yaml:"tagName" mapstructure:"tagName"`
}
